[build]
  publish = "dist"
  command = "rm -rf dist && mkdir -p dist && cp index.html dist/ && echo 'Fresh build complete'"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
